version: "3.8"
services:
  dynamodb-local:
    env_file:
      - ./.env
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  dynamodb-admin:
    env_file:
      - ./.env
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: $DYNAMODB_ENDPOINT
      AWS_REGION: $SAB_AWS_REGION
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
    depends_on:
      - dynamodb-local

  dynamodb-migrator:
    env_file:
      - ./.env
    image: banst/awscli:1.18.76
    container_name: app-dynamodb_migrator
    working_dir: /home/dynamodblocal
    command: dynamodb create-table --cli-input-json file://table-strategy.dynamodb.json --endpoint-url $DYNAMODB_ENDPOINT
    volumes:
      - ./scripts/dynamodb-local/:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
      - AWS_DEFAULT_REGION=$SAB_AWS_REGION
    depends_on:
      - dynamodb-local

volumes:
  app_dynamodb:
    driver: local
